service:
  name: profile-kakaobot

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-warmup

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-2
  state: dev
  memorySize: 128
  timeout: 10
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'

functions:
  keyboard:
    warmup: true
    handler: src/KeyboardHandler.default
    events:
      - http:
          method: get
          path: /keyboard
  message:
    warmup: true
    handler: src/MessageHandler.default
    events:
      - http:
          method: post
          path: /message

custom:
  warmup:
    schedule: rate(5 minutes)
    cleanFolder: false
    memorySize: 128
    timeout: 10
    prewarm: true